name = "anvaya-keyword-tool"
compatibility_date = "2024-01-01"
main = "functions/test-keyword.ts"

[site]
bucket = "dist"

[build]
command = "npm run build"
output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "anvaya-db"
database_id = "1bbf1443-f685-48bf-90b8-0d154e5bd6da"