name = "anvaya-keyword-tool"
compatibility_date = "2024-01-01"

[site]
bucket = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "anvaya-db"
database_id = "1bbf1443-f685-48bf-90b8-0d154e5bd6da"